# debug, release, test
service:
    runmode: release
    addr: :9090
    name: voyager
    url: http://127.0.0.1:9090
    maxPingCount: 10
    jwtSecret: 
log:
    writers: file,stdout # file stdout
    logger_level: DEBUG # DEBUG、INFO、WARN、ERROR、FATAL
    logger_file: /var/log/voyager/runtime.log
    logger_path: /var/log/voyager # log path
    log_format_text: false # false means json, true means text
    rollingPolicy: daily # daily or size
    log_rotate_date: 5
    log_rotate_size: 10 # MB
    log_backup_count: 7
logger:
    logRemain: 10 // Total days of log files to remain
    logDir: "/var/log/voyager"
    reqLogger: "rqlog"
k8s:
    HD2A:
        host: https://k8s.apiserver:443
        token: 
        timeout: 8
        resource:
            cpuOverCommitRate: 2.0
            memOverCommitRate: 2.0
            cpuBurstRate: 1
            memBurstRate: 1
        container:
            imagePullSecret:
                enable: true
                name: 
db:
    name: voyager_server
    addr: 127.0.0.1:3306
    username: username
    password: password
